version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    container_name: database-server
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: ponomarev1986/api_yamdb_infra:latest
    restart: always
    container_name: web-server
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
volumes:
  static_value:
  media_value: